---

- name: "Wordpress Installation - Amazon Linux 2"
  hosts: all
  become: yes
  vars_files:
    - apache.vars
    
  tasks:
    
    - name: "Apache - Installing Apache & Php"
      yum:
        name:
          - httpd
          - php
          - php-mysql
        state: present
      notify:
        - restart-apache
        
    
    - name: "Apache - Creating DocumentRoot"
      file:
        path: "/var/www/html/{{ httpd_domain }}"
        state: directory 
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
      notify:
        - restart-apache
        
            
    - name: "Apache - Creating test.html & test.php"
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ httpd_domain }}/"
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
      with_items:
        - test.php
        - test.html
      notify:
        - restart-apache
        
  handlers:
            
    - name: "restart-apache"
      service:
        name: httpd
        state: restarted
        enabled: true
